services:
  frontend:
    build:
      context: ./frontend # Point to the frontend directory
      dockerfile: Dockerfile.dev # Use the new development Dockerfile
    container_name: ckguru_frontend_dev # Optional: different name for dev container
    volumes:
      - ./frontend:/app # Mount your local frontend source code into the container
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000 (Next.js dev server)
      # We do NOT map port 80 here, as Nginx won't be running in this dev setup for the frontend.
    command: npm run dev # Explicitly set the command for development
    environment:
      # This environment variable is read by Next.js for client-side API calls.
      # It should point to where your backend is accessible from your browser.
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - NODE_ENV=development
      # For some systems (especially Windows or macOS with Docker Desktop),
      # file watching for hot-reloading might need polling. Uncomment if HMR is slow/not working.
      - CHOKIDAR_USEPOLLING=true
