[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 88

[tool.ruff]
line-length = 88
select = ["E", "F", "I"]  # E=pycodestyle, F=pyflakes, I=import order (isort)
fix = true
exclude = ["migrations", "__pycache__"]
ignore = ["E501"]

[tool.ruff.per-file-ignores]
"tests/*" = ["F401"]  # ignore unused imports in tests
