[tool.black]
line-length = 88
target-version = ['py310']

[tool.ruff]
line-length = 88
lint.select = ["E", "F", "I"]  # E=pycodestyle, F=pyflakes, I=import order (isort)
fix = true
exclude = ["migrations", "__pycache__"]
lint.ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["F401"]  # ignore unused imports in tests
