"""add ck_metrics table

Revision ID: 05fbb2c9ea3b
Revises: 3a7d23c079e6
Create Date: 2025-04-01 13:29:07.673052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05fbb2c9ea3b'
down_revision: Union[str, None] = '3a7d23c079e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('git_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('git_url', name='uq_repository_git_url')
    )
    op.create_index(op.f('ix_repositories_git_url'), 'repositories', ['git_url'], unique=True)
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_table('ck_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('class', sa.String(), nullable=True),
    sa.Column('cbo', sa.Float(), nullable=True),
    sa.Column('wmc', sa.Float(), nullable=True),
    sa.Column('dic', sa.Integer(), nullable=True),
    sa.Column('noc', sa.Integer(), nullable=True),
    sa.Column('rfc', sa.Float(), nullable=True),
    sa.Column('lcom', sa.Float(), nullable=True),
    sa.Column('lcom*', sa.Float(), nullable=True),
    sa.Column('loc', sa.Integer(), nullable=True),
    sa.Column('dit', sa.Integer(), nullable=True),
    sa.Column('nosi', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ck_metrics_commit_hash'), 'ck_metrics', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_ck_metrics_id'), 'ck_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_ck_metrics_repository_id'), 'ck_metrics', ['repository_id'], unique=False)
    op.drop_index('ix_repository_git_url', table_name='repository')
    op.drop_index('ix_repository_id', table_name='repository')
    op.drop_index('ix_repository_name', table_name='repository')
    op.drop_table('repository')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('git_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='repository_pkey')
    )
    op.create_index('ix_repository_name', 'repository', ['name'], unique=False)
    op.create_index('ix_repository_id', 'repository', ['id'], unique=False)
    op.create_index('ix_repository_git_url', 'repository', ['git_url'], unique=True)
    op.drop_index(op.f('ix_ck_metrics_repository_id'), table_name='ck_metrics')
    op.drop_index(op.f('ix_ck_metrics_id'), table_name='ck_metrics')
    op.drop_index(op.f('ix_ck_metrics_commit_hash'), table_name='ck_metrics')
    op.drop_table('ck_metrics')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_git_url'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
