"""clean

Revision ID: 231678376d15
Revises: 
Create Date: 2025-04-03 14:55:27.413806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231678376d15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('git_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('git_url', name='uq_repository_git_url')
    )
    op.create_index(op.f('ix_repositories_git_url'), 'repositories', ['git_url'], unique=True)
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_table('ck_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('class', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('cbo', sa.Float(), nullable=True),
    sa.Column('cboModified', sa.Float(), nullable=True),
    sa.Column('fanin', sa.Integer(), nullable=True),
    sa.Column('fanout', sa.Integer(), nullable=True),
    sa.Column('wmc', sa.Float(), nullable=True),
    sa.Column('dit', sa.Integer(), nullable=True),
    sa.Column('noc', sa.Integer(), nullable=True),
    sa.Column('rfc', sa.Float(), nullable=True),
    sa.Column('lcom', sa.Float(), nullable=True),
    sa.Column('lcom*', sa.Float(), nullable=True),
    sa.Column('tcc', sa.Float(), nullable=True),
    sa.Column('lcc', sa.Float(), nullable=True),
    sa.Column('totalMethodsQty', sa.Integer(), nullable=True),
    sa.Column('staticMethodsQty', sa.Integer(), nullable=True),
    sa.Column('publicMethodsQty', sa.Integer(), nullable=True),
    sa.Column('privateMethodsQty', sa.Integer(), nullable=True),
    sa.Column('protectedMethodsQty', sa.Integer(), nullable=True),
    sa.Column('defaultMethodsQty', sa.Integer(), nullable=True),
    sa.Column('visibleMethodsQty', sa.Integer(), nullable=True),
    sa.Column('abstractMethodsQty', sa.Integer(), nullable=True),
    sa.Column('finalMethodsQty', sa.Integer(), nullable=True),
    sa.Column('synchronizedMethodsQty', sa.Integer(), nullable=True),
    sa.Column('totalFieldsQty', sa.Integer(), nullable=True),
    sa.Column('staticFieldsQty', sa.Integer(), nullable=True),
    sa.Column('publicFieldsQty', sa.Integer(), nullable=True),
    sa.Column('privateFieldsQty', sa.Integer(), nullable=True),
    sa.Column('protectedFieldsQty', sa.Integer(), nullable=True),
    sa.Column('defaultFieldsQty', sa.Integer(), nullable=True),
    sa.Column('finalFieldsQty', sa.Integer(), nullable=True),
    sa.Column('synchronizedFieldsQty', sa.Integer(), nullable=True),
    sa.Column('nosi', sa.Integer(), nullable=True),
    sa.Column('loc', sa.Integer(), nullable=True),
    sa.Column('returnQty', sa.Integer(), nullable=True),
    sa.Column('loopQty', sa.Integer(), nullable=True),
    sa.Column('comparisonsQty', sa.Integer(), nullable=True),
    sa.Column('tryCatchQty', sa.Integer(), nullable=True),
    sa.Column('parenthesizedExpsQty', sa.Integer(), nullable=True),
    sa.Column('stringLiteralsQty', sa.Integer(), nullable=True),
    sa.Column('numbersQty', sa.Integer(), nullable=True),
    sa.Column('assignmentsQty', sa.Integer(), nullable=True),
    sa.Column('mathOperationsQty', sa.Integer(), nullable=True),
    sa.Column('variablesQty', sa.Integer(), nullable=True),
    sa.Column('maxNestedBlocksQty', sa.Integer(), nullable=True),
    sa.Column('anonymousClassesQty', sa.Integer(), nullable=True),
    sa.Column('innerClassesQty', sa.Integer(), nullable=True),
    sa.Column('lambdasQty', sa.Integer(), nullable=True),
    sa.Column('uniqueWordsQty', sa.Integer(), nullable=True),
    sa.Column('modifiers', sa.Integer(), nullable=True),
    sa.Column('logStatementsQty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ck_metrics_class'), 'ck_metrics', ['class'], unique=False)
    op.create_index(op.f('ix_ck_metrics_commit_hash'), 'ck_metrics', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_ck_metrics_file'), 'ck_metrics', ['file'], unique=False)
    op.create_index(op.f('ix_ck_metrics_id'), 'ck_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_ck_metrics_repository_id'), 'ck_metrics', ['repository_id'], unique=False)
    op.create_table('commit_guru_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('parent_hashes', sa.String(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('author_email', sa.String(), nullable=True),
    sa.Column('author_date', sa.String(), nullable=True),
    sa.Column('author_date_unix_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('is_buggy', sa.Boolean(), nullable=False),
    sa.Column('fix', sa.Boolean(), nullable=True),
    sa.Column('fixing_commit_hashes', sa.JSON(), nullable=True),
    sa.Column('files_changed', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ns', sa.Float(), nullable=True),
    sa.Column('nd', sa.Float(), nullable=True),
    sa.Column('nf', sa.Float(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('la', sa.Float(), nullable=True),
    sa.Column('ld', sa.Float(), nullable=True),
    sa.Column('lt', sa.Float(), nullable=True),
    sa.Column('ndev', sa.Float(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('nuc', sa.Float(), nullable=True),
    sa.Column('exp', sa.Float(), nullable=True),
    sa.Column('rexp', sa.Float(), nullable=True),
    sa.Column('sexp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'commit_hash', name='uq_commit_guru_metric')
    )
    op.create_index(op.f('ix_commit_guru_metrics_commit_hash'), 'commit_guru_metrics', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_commit_guru_metrics_id'), 'commit_guru_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_commit_guru_metrics_is_buggy'), 'commit_guru_metrics', ['is_buggy'], unique=False)
    op.create_index(op.f('ix_commit_guru_metrics_repository_id'), 'commit_guru_metrics', ['repository_id'], unique=False)
    op.create_table('github_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('created_at_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('closed_at_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('html_url', sa.String(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('etag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('repository_id', 'issue_number', name='uq_repo_issue_number')
    )
    op.create_index(op.f('ix_github_issues_id'), 'github_issues', ['id'], unique=False)
    op.create_index(op.f('ix_github_issues_issue_number'), 'github_issues', ['issue_number'], unique=False)
    op.create_index(op.f('ix_github_issues_repository_id'), 'github_issues', ['repository_id'], unique=False)
    op.create_table('commit_github_issue_association',
    sa.Column('commit_guru_metric_id', sa.Integer(), nullable=False),
    sa.Column('github_issue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commit_guru_metric_id'], ['commit_guru_metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['github_issue_id'], ['github_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commit_guru_metric_id', 'github_issue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commit_github_issue_association')
    op.drop_index(op.f('ix_github_issues_repository_id'), table_name='github_issues')
    op.drop_index(op.f('ix_github_issues_issue_number'), table_name='github_issues')
    op.drop_index(op.f('ix_github_issues_id'), table_name='github_issues')
    op.drop_table('github_issues')
    op.drop_index(op.f('ix_commit_guru_metrics_repository_id'), table_name='commit_guru_metrics')
    op.drop_index(op.f('ix_commit_guru_metrics_is_buggy'), table_name='commit_guru_metrics')
    op.drop_index(op.f('ix_commit_guru_metrics_id'), table_name='commit_guru_metrics')
    op.drop_index(op.f('ix_commit_guru_metrics_commit_hash'), table_name='commit_guru_metrics')
    op.drop_table('commit_guru_metrics')
    op.drop_index(op.f('ix_ck_metrics_repository_id'), table_name='ck_metrics')
    op.drop_index(op.f('ix_ck_metrics_id'), table_name='ck_metrics')
    op.drop_index(op.f('ix_ck_metrics_file'), table_name='ck_metrics')
    op.drop_index(op.f('ix_ck_metrics_commit_hash'), table_name='ck_metrics')
    op.drop_index(op.f('ix_ck_metrics_class'), table_name='ck_metrics')
    op.drop_table('ck_metrics')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_git_url'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
