"""add unique constraint to ck_metrics table

Revision ID: 36332747d491
Revises: fbe548d9518a
Create Date: 2025-04-29 18:57:52.150393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36332747d491'
down_revision: Union[str, None] = 'fbe548d9518a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ck_metric_key', 'ck_metrics', ['repository_id', 'commit_hash', 'file', 'class'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ck_metric_key', 'ck_metrics', type_='unique')
    # ### end Alembic commands ###
