"""add commit_guru_metrics table

Revision ID: 38f0cc600dcb
Revises: 48f8433d8d73
Create Date: 2025-04-02 12:26:03.937226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f0cc600dcb'
down_revision: Union[str, None] = '48f8433d8d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commit_guru_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('parent_hashes', sa.String(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('author_date_unix_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('is_buggy', sa.Boolean(), nullable=False),
    sa.Column('fixing_commit_hashes', sa.JSON(), nullable=True),
    sa.Column('ns', sa.Float(), nullable=True),
    sa.Column('nd', sa.Float(), nullable=True),
    sa.Column('nf', sa.Float(), nullable=True),
    sa.Column('entropy', sa.Float(), nullable=True),
    sa.Column('la', sa.Float(), nullable=True),
    sa.Column('ld', sa.Float(), nullable=True),
    sa.Column('lt', sa.Float(), nullable=True),
    sa.Column('ndev', sa.Float(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('nuc', sa.Float(), nullable=True),
    sa.Column('exp', sa.Float(), nullable=True),
    sa.Column('rexp', sa.Float(), nullable=True),
    sa.Column('sexp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commit_guru_metrics_commit_hash'), 'commit_guru_metrics', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_commit_guru_metrics_id'), 'commit_guru_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_commit_guru_metrics_is_buggy'), 'commit_guru_metrics', ['is_buggy'], unique=False)
    op.create_index(op.f('ix_commit_guru_metrics_repository_id'), 'commit_guru_metrics', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commit_guru_metrics_repository_id'), table_name='commit_guru_metrics')
    op.drop_index(op.f('ix_commit_guru_metrics_is_buggy'), table_name='commit_guru_metrics')
    op.drop_index(op.f('ix_commit_guru_metrics_id'), table_name='commit_guru_metrics')
    op.drop_index(op.f('ix_commit_guru_metrics_commit_hash'), table_name='commit_guru_metrics')
    op.drop_table('commit_guru_metrics')
    # ### end Alembic commands ###
