"""create repositories table

Revision ID: 3a7d23c079e6
Revises: 
Create Date: 2025-03-31 21:47:33.143825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7d23c079e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('git_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_git_url'), 'repository', ['git_url'], unique=True)
    op.create_index(op.f('ix_repository_id'), 'repository', ['id'], unique=False)
    op.create_index(op.f('ix_repository_name'), 'repository', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_name'), table_name='repository')
    op.drop_index(op.f('ix_repository_id'), table_name='repository')
    op.drop_index(op.f('ix_repository_git_url'), table_name='repository')
    op.drop_table('repository')
    # ### end Alembic commands ###
