"""change lcom* column name to lcom_norm

Revision ID: 3fa95af1143b
Revises: 36332747d491
Create Date: 2025-05-03 21:49:54.364984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa95af1143b'
down_revision: Union[str, None] = '36332747d491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'ck_metrics',
        'lcom*',
        existing_type=sa.Float(),
        existing_nullable=True,
        nullable=True,
        new_column_name='lcom_norm',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'ck_metrics',
        'lcom_norm',
        existing_type=sa.Float(),
        existing_nullable=True,
        nullable=True,
        new_column_name='lcom*',
    )
    # ### end Alembic commands ###
