"""add_github_issue_fields_to_commit_guru

Revision ID: 7d5b0b1799a9
Revises: de7f1fc9e6c5
Create Date: 2025-04-02 14:05:12.515547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5b0b1799a9'
down_revision: Union[str, None] = 'de7f1fc9e6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit_guru_metrics', sa.Column('github_issue_ids', sa.JSON(), nullable=True))
    op.add_column('commit_guru_metrics', sa.Column('github_earliest_issue_open_timestamp', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commit_guru_metrics', 'github_earliest_issue_open_timestamp')
    op.drop_column('commit_guru_metrics', 'github_issue_ids')
    # ### end Alembic commands ###
