"""add_more_commit_guru_fields

Revision ID: de7f1fc9e6c5
Revises: 38f0cc600dcb
Create Date: 2025-04-02 13:13:00.104288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7f1fc9e6c5'
down_revision: Union[str, None] = '38f0cc600dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commit_guru_metrics', sa.Column('author_email', sa.String(), nullable=True))
    op.add_column('commit_guru_metrics', sa.Column('author_date', sa.String(), nullable=True))
    op.add_column('commit_guru_metrics', sa.Column('commit_message', sa.Text(), nullable=True))
    op.add_column('commit_guru_metrics', sa.Column('fix', sa.Boolean(), nullable=True))
    op.add_column('commit_guru_metrics', sa.Column('files_changed', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_commit_guru_metric', 'commit_guru_metrics', ['repository_id', 'commit_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_commit_guru_metric', 'commit_guru_metrics', type_='unique')
    op.drop_column('commit_guru_metrics', 'files_changed')
    op.drop_column('commit_guru_metrics', 'fix')
    op.drop_column('commit_guru_metrics', 'commit_message')
    op.drop_column('commit_guru_metrics', 'author_date')
    op.drop_column('commit_guru_metrics', 'author_email')
    # ### end Alembic commands ###
