# shared/schemas/__init__.py
from .bot_pattern import (
    BotPatternBase,
    BotPatternCreate,
    BotPatternRead,
    BotPatternUpdate,
    PaginatedBotPatternRead,  # Ensure this is imported
)
from .dataset import (
    DatasetBase,
    DatasetConfig,
    DatasetCreate,
    DatasetRead,
    DatasetStatusUpdate,
    DatasetTaskResponse,
    PaginatedDatasetRead,
)
from .enums import (
    DatasetStatusEnum,
    JobStatusEnum,
    ModelTypeEnum,
    ObjectiveMetricEnum,
    PrunerTypeEnum,
    SamplerTypeEnum,
)
from .hp_search_job import (
    HPSearchConfig,
    HPSearchJobBase,
    HPSearchJobCreate,
    HPSearchJobRead,
    HPSearchJobSubmitResponse,
    HPSearchJobUpdate,
    HPSuggestion,
    OptunaConfig,
    PaginatedHPSearchJobRead, 
)
from .inference import (
    GitHubPushPayload,
    InferenceTriggerResponse,
    ManualInferenceRequest,
)
from .inference_job import (
    InferenceJobBase,
    InferenceJobRead,
    InferenceJobUpdate,
    PaginatedInferenceJobRead, 
)
from .inference_job import (
    InferenceJobCreateInternal as InferenceJobCreate,  # Use alias for creation
)
from .ml_model import (
    MLModelBase,
    MLModelCreate,
    MLModelRead,
    MLModelUpdate,
    PaginatedMLModelRead, 
)
from .repo_api_client import RepoApiClientResponse, RepoApiResponseStatus
from .repository import (
    RepositoryBase,
    RepositoryCreate,
    RepositoryInDB,
    RepositoryRead,
    RepositoryUpdate,
    PaginatedRepositoryRead,
)
from .rule_definition import RuleDefinition, RuleParamDefinition
from .task import TaskResponse, TaskStatusEnum, TaskStatusResponse
from .training_job import (
    TrainingRunConfig,
    TrainingJobBase,
    TrainingJobCreate,
    TrainingJobRead,
    TrainingJobSubmitResponse,
    TrainingJobUpdate,
    PaginatedTrainingJobRead, 
)
from .xai import (
    CounterfactualExample,
    CounterfactualResultData,
    DecisionPathEdge,
    DecisionPathNode,
    DecisionPathResultData,
    FeatureImportanceResultData,
    FeatureImportanceValue,
    FeatureSHAPValue,
    FilePredictionDetail,
    InstanceCounterfactualResult,
    InstanceDecisionPath,
    InstanceLIMEResult,
    InstanceSHAPResult,
    LIMEResultData,
    SHAPResultData,
)
from .xai_job import XAIResultBase, XAIResultCreate, XAIResultRead, XAIResultUpdate
from .dashboard import DashboardSummaryStats, DatasetsByStatus

__all__ = [
    # Enums
    "JobStatusEnum",
    "DatasetStatusEnum",
    "ObjectiveMetricEnum",
    "SamplerTypeEnum",
    "PrunerTypeEnum",
    "ModelTypeEnum",
    "XAITypeEnum",
    "XAIStatusEnum",
    "TaskStatusEnum",
    # Schemas
    "RepositoryBase",
    "RepositoryCreate",
    "RepositoryRead",
    "RepositoryUpdate",
    "RepositoryInDB",
    "PaginatedRepositoryRead",
    "TaskResponse",
    "TaskStatusResponse",
    "BotPatternBase",
    "BotPatternCreate",
    "BotPatternRead",
    "BotPatternUpdate",
    "PaginatedBotPatternRead", 
    "DatasetBase",
    "DatasetCreate",
    "DatasetRead",
    "DatasetConfig",
    "DatasetStatusUpdate",
    "DatasetTaskResponse",
    "RuleDefinition",
    "RuleParamDefinition",
    "MLModelBase",
    "MLModelCreate",
    "MLModelRead",
    "MLModelUpdate",
    "PaginatedMLModelRead", 
    "TrainingJobBase",
    "TrainingJobCreate",
    "TrainingJobRead",
    "TrainingJobUpdate",
    "TrainingRunConfig",
    "TrainingJobSubmitResponse",
    "PaginatedTrainingJobRead",  
    "HPSearchJobBase",
    "HPSearchJobCreate",
    "HPSearchJobUpdate",
    "HPSearchJobRead",
    "HPSearchConfig",
    "OptunaConfig",
    "HPSuggestion",
    "HPSearchJobSubmitResponse",
    "PaginatedHPSearchJobRead",  
    "InferenceJobBase",
    "InferenceJobCreate",
    "InferenceJobUpdate",
    "InferenceJobRead",
    "ManualInferenceRequest",
    "InferenceTriggerResponse",
    "PaginatedInferenceJobRead", 
    "GitHubPushPayload",
    "RepoApiResponseStatus",
    "RepoApiClientResponse",
    "CounterfactualExample",
    "CounterfactualResultData",
    "DecisionPathNode",
    "DecisionPathEdge",
    "DecisionPathResultData",
    "FeatureImportanceResultData",
    "FeatureImportanceValue",
    "FeatureSHAPValue",
    "FilePredictionDetail",
    "InstanceCounterfactualResult",
    "InstanceDecisionPath",
    "InstanceLIMEResult",
    "InstanceSHAPResult",
    "LIMEResultData",
    "SHAPResultData",
    "XAIResultBase",
    "XAIResultCreate",
    "XAIResultRead",
    "XAIResultUpdate",
    "PaginatedDatasetRead",
    "DashboardSummaryStats",
    "DatasetsByStatus",
]
